/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package auth.ece.app;

import lombok.extern.log4j.Log4j2;

import java.net.URI;
import java.net.URISyntaxException;
import java.nio.file.Path;
import java.nio.file.Paths;

@Log4j2
public class App {
    public static void main(String[] args) {
        execute();
    }

    public static void execute() {
        URI loc;
        try {
            loc = ClassLoader.getSystemResource("dataset/edf/household_power_consumption.txt").toURI();
            Path path = Paths.get(loc);
            NilmReader nilmReader = new NilmReader();
            nilmReader.readFile(path);
        } catch (URISyntaxException e) {
            log.error("URI syntax not correct, please check");
        }
    }
}
